### PR TITLE
bug fix: filter out empty headings so button functionality works

### PR DESCRIPTION
**Pull request by CarlyGerard**
I noticed what I think might be a bug or a behavior that could impact users' ability to navigate using SkipTo, so I'm offering a patch that should resolve the error I'm seeing. (Note: we're using Drupal as our CMS if that's a factor.)

## Expected behavior
If a page has an empty heading (example: `<h2>&nbsp;</h2>`), SkipTo ignores it from the list of meaningful headings options for a user to choose.

## Current behavior
If a page contains empty headings, the SkipTo menu won't open at all with Space, Enter, or the keyboard shortcut. In the console, the following error registers, probably due to the label not having text content to trim since it's whitespace:

Uncaught TypeError: label.textContent.trim() is undefined

This happens in Chrome/Firefox/Safari from my testing so far, and prevents people from using SkipTo entirely since the menu won't open with this error.

## Reasoning
Ideally headings shouldn't be empty anyway, or used for spacing. Still, mistakes can be made due to lack of editor awareness, or WYSIWYG editor bugs that don't strip out HTML heading markup as expected. It seems fairer to the site visitor to let them continue using SkipTo as a way to bypass content, but ignore the 'headings' that aren't meaningful sections to get to.

I'm open to feedback or other ways to go about this issue though.

### CODE REVIEW

**Comment by brianteeman** [comment]
Firstly I can confirm that skipto falls over if there is an empty heading as you describe although my console error is different.

```
skipto.min.js?4.1.3:7 Uncaught TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at Object.getFirstChar (skipto.min.js?4.1.3:7)
    at Object.updateKeyboardShortCuts (skipto.min.js?4.1.3:7)
    at Object.updateMenuitems (skipto.min.js?4.1.3:7)
    at Object.renderMenu (skipto.min.js?4.1.3:7)
    at Object.openPopup (skipto.min.js?4.1.3:7)
    at Object.handleButtonKeydown (skipto.min.js?4.1.3:7)
```

I'm not sure about trying to fix it though. The empty heading is an accessibility failure

**Comment by CarlyGerard** [comment]
@brianteeman thanks for responding and taking a look. Certainly agreed that empty headings are an accessibility issue not just for skip-to, but for plenty of other reasons. At the same time, it seems delicate that an empty heading could break the entire library and ability to bypass repeated sections of content, another accessibility failure that could impact people navigating by keyboard-only, speech recognition, stick or switch devices, etc.

I've also noticed in text editors like CKEditor that depending on how text is removed, the heading markup could stay, leaving an empty tag behind. If an editor removes text and doesn't realize that happened (particularly those using rich content mode, maybe not as HTML-savvy to realize that happened), they've blocked someone from skipping repeated content sections without realizing it. 

I could be coming at this from more of a web platform management side of things, where our team is not in every subdomain's content daily. While we provide training and documentation on correct heading usage and manage overall web platforms, we can't always guarantee someone is using headings correctly, unfortunately. 

In that use case, I don't want a person visiting our site to face navigation barriers because of that error, so ensuring the functionality at least doesn't break would greatly help. If there's a better way to address that concern from SkipTo's side, I'd be interested in getting your thoughts on that.

**Comment by brianteeman** [comment]
I think I will leave a decision on the code to @jongund as I just don't agree in hiding issues.

I appreciate however that you clearly have an issue with empty headings being created by drupal/ckeditor and that you need a solution to that.

It is only suggestion but I would recommend that you look at the drupal module "editoria11y". It is an accessibility checker that runs on your content and is designed for your content authors to resolve issues (and learn from them) at the time of creation.

**Comment by jongund** [comment]
@CarlyGerard 
Thank you for identifying this issue and submitting a pull request.
I think we definitely don't want SkipTo to break on empty headings, so the code looks good, so I think we should merge and I will create a test page to make sure we can test for the feature in future versions.

**Comment by CarlyGerard** [comment]
Thanks @jongund and @brianteeman again for your thoughts, I'm grateful for your expertise on this. 

For a console message, is the idea that SkipTo would still work even with empty headings, but the console also alerts there are empty headings to address? That could be helpful for those working in dev tools. 

I'm not sure if all content creators/editors will be looking in dev tools, or whether SkipTo should even address it from that side of things. That's an accessibility checker's job for sure to alert that, but I'll leave that up to you all as the maintainers to decide whether SkipTo should flag that issue in any way. As long as SkipTo doesn't break navigation on something like an empty heading, I'll go with your best judgment.

I'm also okay with this PR being more of a patch in the meantime, if this needs more looking at and a better-aligned approach in a future release.

**Comment by brianteeman** [comment]
What about instead of hiding the problem completely have skipto output an empty heading so it would like this.

image

**Pull request merged**
