### PR TITLE
Joomla

### PR DESCRIPTION
**Pull request by brianteeman**
Add reference to Joomla in the readme

### CODE REVIEW

**Comment by jongund** [comment]
@brianteeman 
The `index.md` file should remove the references to Drupal and WordPress plugins since I don't think either of those plugins are compatible with the latest versions and I don't see any activity in trying to maintain them.  I removed them from the `readme.md` long ago.

**Comment by brianteeman** [comment]
removed them

**Comment by jongund** [comment]
Seems like this could be removed too, I don't think they would work:

To sweeten your day even more, the GreaseMonkey script and Safari bookmarklet are also available. See the "downloads" section below for related links.By the way, this page is a great chance to see the "SkipTo menu" in action! Did you find the menu at the top?

**Comment by brianteeman** [comment]
and done. 

I will put removing the drupal and wordpress stuff from the repo on my todo list

**Comment by jongund** [comment]
Looks good, I think you can merge when your ready.

**Pull request merged**
