### PR TITLE
Fixed bug with invalid CSS template variable and use of role-description for class name

### PR DESCRIPTION
**Pull request by jongund**
* Fixed bug in using role description as a class name for menuitem
* Fixed bug in setting `menuTextColor` property.
* Updated documentation.

### CODE REVIEW

**Comment by jongund** [comment]
@brianteeman 
Found another bug that needed fixing, and I restored the the class name 'action'.

**Comment by brianteeman** [comment]
As i stated previously I don't see the purpose of the cdn document to this repo as its only relevant to the university. especially as the commands look like they  might even include some credentials

**Comment by jongund** [comment]
@brianteeman 
Removed the cdn documentation file

**Comment by jongund** [comment]
@mpnkhan 
Are there any concerns about this pull request?

**Comment by jongund** [comment]
@mpnkhan 
Thank you!

**Pull request merged**
