### PR TITLE
Added aria-busy and aria-controls to button and menu

### PR DESCRIPTION
**Pull request by jongund**
Some accessibility validators were flagging the hidden empty menu when the script is initially loaded as an ARIA validation error, since menus have required menu item children.  Before the menu is made visible, it has the required menu items.  
In general I don't think validators should not fail hidden content, but I added aria-busy=true to indicate that the menu is not ready yet, so if validators follow the spec they should not fail the menu.  While `aria-controls` attribute is not required for the button, it is a recommended option in the ARIA authoring practice, so I want to use it in SkipTo.  
  
I also found some problems with documentation and updated the `README.md` file.

### CODE REVIEW

**Comment by brianteeman** [comment]
I will check everything by the weekend and merge it and make a new release on npm.  I have a few other small fixes to include.

**Comment by brianteeman** [comment]
@jongund looks like you forgot to add the new code. There is just the readme here.

**Comment by jongund** [comment]
@brianteeman 
Thanks for pointing out the problem.
Somehow my fork got out of synch with paypal, so the changed files are now showing up, but the diffs in skipto.js are not highlighted correctly.  There are not that many, just adding the `aria-busy` code and `aria-controls` reference.

**Comment by brianteeman** [comment]
If it's ok with you I will merge my pull requests and yours and make a new release.

**Comment by brianteeman** [comment]
OK will do. Run out of time today but will do it on Sunday

**Comment by vick08** [comment]
Apologies if I am missing the context here, but I am not sure that it is advantageous for the user to jump to the aria-busy region. The rationale behind the "skipto" menu is to help users to move to the visible, interactive controls and regions critical for the navigation on the website.
Why would the users need to jump to the "aria-busy" region, especially that this only has a meaning in the context of assistive technology?
Just wondering...

**Comment by jongund** [comment]
@vick08 
Sorry about any confusion over adding `aria-busy` attribute.  The `aria-busy=true` attribute is only set on the element with the `menu` role when the menu is initially empty, or when the menu items are being updated after the user presses the button.  It doesn't effect navigation to regions on a web page.  The `aria-busy` attribute is removed when the menu has menu items, which is populated every time the user selects the "Skip To Content" button.  The `aria-busy` attribute is being added to keep validators from flagging an error when the element with the menu role doesn't have any menu items.  ARIA requires a menu to have menu items, unless the `aria-busy` attribute is set to `true`.

**Comment by brianteeman** [comment]
Not sure what has happened @jongund but your repo has a 4.1.1 release with
` * Removed <code>aria-describedby</code> from button, since screen readers read the <code>accesskey</code> information.
` but this was never submitted to this repo and released.

I am going to build a new pr here with all your 4.1.1 changes and your 4,1.2 changes (directly from your repo) and release that as 4.1.2.

Your github pages pr will probably also need to be closed and rebuilt as 99% of the changes are made automatically whenever a release is made. But I will check what is created and update it if necessary with the suggestions from your other PR

**Pull request closed without merging**
